### ISSUE TITLE
stworzenie tabel do przechowywania wiadomości prywatnych

### ISSUE THREAD

**Issue by sikora195703** [sikora195703/jcom#26]
Trzeba stworzyć tabele:  conversations(conversation_id, user1, user2),  private_messages(message_id, conversation_id, sender, content, send_date). Na send_date powinien być index i pary user1, user2 unikalne. Po stronie serwera potrzebna będzie metoda zwracająca listę wszystkich wiadomości(ChatMessage) dla pary użytkowników(kolejność ich podania nie ma znaczenia) posortowaną po dacie wysłania.

**Comment by babyak199184** [comment]
Moze przechowywac zdjecia w bazie typu BLOB? Czy zostawic jak jest teraz przez wskazanie zciezki?
